## **Concating PST and EML**

In [4]:
import pandas as pd
from pathlib import Path

df_pst_all = pd.read_parquet("../data/processed/pst_parsed/parsed_pst_all.parquet")

print(df_pst_all.shape)
df_pst_all.head()

(214803, 21)

,id,subject,sender,sender_email,to,cc,date,body,recipient_emails,recipient_names,...,folder_path,has_attachments,attachment_count,attachment_names,headers,message_id,in_reply_to,references,source_type,source_file
0,2097988,答复: Stem cell medium technology purchase,LUO Rose,may8209@hotmail.com,judy.tse@promabinc.com,feihongoz@163.com,2018-02-28 00:41:33,"Dear Judy,\r\n\r\nThanks for your email.\r\n\r...",,,...,/Top of Outlook data file/Inbox,True,1,[image001.png],Delivered-To: judy.tse@promabinc.com\r\nReceiv...,<SG2PR01MB05698D16EC605F51C53192EFB9C70@SG2PR0...,<015001d3b023$013f83c0$03be8b40$@promabinc.com>,<HK2PR01MB05623323251A60276ECE25C9B9C00@HK2PR0...,pst,judy.tse@promabinc.com(4).pst
1,2098692,RE: Hybridoma Supernatant Timing,"Bates, Barbara",BBates@morgridge.org,judy.tse@promabinc.com,,2018-03-01 22:29:37,"Hello, \r\n\r\nI did receive your email. I thi...",,,...,/Top of Outlook data file/Inbox,False,0,[],Delivered-To: judy.tse@promabinc.com\r\nReceiv...,<F8B22F7FE52FD14FAAFB9ADA4F8DA9906AD43631@MIRI...,<012301d3b1ac$74187ed0$5c497c70$@promabinc.com>,<F8B22F7FE52FD14FAAFB9ADA4F8DA990585ADF22@MIRI...,pst,judy.tse@promabinc.com(4).pst
2,2098852,RE: Hybridoma Supernatant Timing,"Bates, Barbara",BBates@morgridge.org,judy.tse@promabinc.com,,2018-03-01 22:44:17,"I should have a formal PO to send tomorrow, bu...",,,...,/Top of Outlook data file/Inbox,False,0,[],Delivered-To: judy.tse@promabinc.com\r\nReceiv...,<F8B22F7FE52FD14FAAFB9ADA4F8DA9906AD4365B@MIRI...,<012301d3b1ac$74187ed0$5c497c70$@promabinc.com>,<F8B22F7FE52FD14FAAFB9ADA4F8DA990585ADF22@MIRI...,pst,judy.tse@promabinc.com(4).pst
3,2098948,答复: Stem cell medium technology purchase,LUO Rose,may8209@hotmail.com,judy.tse@promabinc.com,feihongoz@163.com,2018-03-02 12:20:48,"Dear Judy,\r\n\r\nWhat time will you be availa...",,,...,/Top of Outlook data file/Inbox,True,2,"[~WRD180.jpg, image001.png]",Delivered-To: judy.tse@promabinc.com\r\nReceiv...,<HK2PR01MB05621EF9E4B9BFB7CA37F52CB9C50@HK2PR0...,<01bc01d3b0cd$c7820e90$56862bb0$@promabinc.com>,<HK2PR01MB05623323251A60276ECE25C9B9C00@HK2PR0...,pst,judy.tse@promabinc.com(4).pst
4,2099268,RE: Stem cell medium technology purchase,john@promab.com,john@promab.com,judy.tse@promabinc.com,,2018-03-02 17:13:38,"Ask their wechat number so, we can call on wee...",,,...,/Top of Outlook data file/Inbox,True,2,"[image001.png, image002.jpg]",Delivered-To: judy.tse@promabinc.com\r\nReceiv...,<06f301d3b249$ccb27300$66175900$@promab.com>,<008f01d3b247$8b0e2ae0$a12a80a0$@promabinc.com>,<HK2PR01MB05623323251A60276ECE25C9B9C00@HK2PR0...,pst,judy.tse@promabinc.com(4).pst

In [5]:
df_pst_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 214803 entries, 0 to 214802
Data columns (total 21 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                214803 non-null  int64
 1   subject           214803 non-null  str
 2   sender            214803 non-null  str
 3   sender_email      214803 non-null  str
 4   to                214803 non-null  str
 5   cc                214803 non-null  str
 6   date              214800 non-null  datetime64[us]
 7   body              214803 non-null  str
 8   recipient_emails  214803 non-null  str
 9   recipient_names   214803 non-null  str
 10  source_pst        214803 non-null  str
 11  folder_path       214803 non-null  str
 12  has_attachments   214803 non-null  bool
 13  attachment_count  214803 non-null  int64
 14  attachment_names  214803 non-null  object
 15  headers           214803 non-null  str
 16  message_id        214803 non-null  str
 17  in_reply_to       214803 non-null  str
 18  references        214803 non-null  str
 19  source_type       214803 non-null  str
 20  source_file       214803 non-null  str
dtypes: bool(1), datetime64[us](1), int64(2), object(1), str(16)
memory usage: 1.4+ GB

In [8]:
df_eml_all = pd.read_parquet("../data/processed/eml_parsed/parsed_eml_all.parquet")

print(df_eml_all.shape)
df_eml_all.head()

(13941, 21)

,id,subject,sender,sender_email,to,cc,date,body,recipient_emails,recipient_names,...,folder_path,has_attachments,attachment_count,attachment_names,headers,message_id,in_reply_to,references,source_type,source_file
0,11355263627102,FW: FW: Promab Hybridoma Sequencing. - Laura P...,Judy Tse,judy.tse@promab.com,Martyn Lewis <martyn.lewis@promab.com>,,2015-04-13 09:55:31,"Hi.\n\nWhen you have time, could you please ch...",martyn.lewis@promab.com,Martyn Lewis,...,/Users/promab/anaconda_projects/email_agent/da...,True,1,[91247-BH6 variable region sequence result.docx],X-Antivirus: Avast (VPS 15042801)\nX-Antivirus...,<019801d0760a$a8af0fa0$fa0d2ee0$@promab.com>,,,eml,FW- FW- Promab Hybridoma Sequencing. - Laura P...
1,76313927896914,Re: Custom Rabbit Monoclonal Antibody Service ...,"Gangwani, Laxman",laxman.gangwani@ttuhsc.edu,Martyn Lewis <martyn.lewis@promab.com>,,2015-02-27 14:58:44,"Do you need anything else?\n\nThanks,\n\n--\nL...",martyn.lewis@promab.com,Martyn Lewis,...,/Users/promab/anaconda_projects/email_agent/da...,False,0,[],X-Antivirus: Avast (VPS 15022601)\nX-Antivirus...,<D11644B3.1555A%laxman.gangwani@ttuhsc.edu>,<54EF1E1E.8040806@promab.com>,,eml,Re- Custom Rabbit Monoclonal Antibody Service ...
2,69581235304569,RE: Biocare/Weimin New Quotes,Judy Tse,judy.tse@promab.com,Martyn Lewis <martyn.lewis@promab.com>,,2015-04-23 09:15:09,"Woops, I should mention the target is CD274. T...",martyn.lewis@promab.com,Martyn Lewis,...,/Users/promab/anaconda_projects/email_agent/da...,False,0,[],X-Antivirus: Avast (VPS 15042801)\nX-Antivirus...,<01f601d07de0$aceb4330$06c1c990$@promab.com>,<01ec01d07de0$8e148480$aa3d8d80$@promab.com>,<035301d07d3a$7bf91140$73eb33c0$@promab.com> <...,eml,RE- Biocare-Weimin New Quotes[4].eml
3,132063061765019,Wave Goodbye to Phone-Bills - VoIP Home & Busi...,VoIP Phone Setup,VoIPPhoneSetup@unequalcrbier.xyz,martyn.lewis@promab.com,,2016-01-07 12:51:35,"<!DOCTYPE html PUBLIC ""-//W3C//DTD XHTML 1.0 T...",martyn.lewis@promab.com,,...,/Users/promab/anaconda_projects/email_agent/da...,False,0,[],X-Antivirus: Avast (VPS 16010600)\nX-Antivirus...,<u22444786o22444786.22444786_martyn.lewis@prom...,,,eml,Wave Goodbye to Phone-Bills - VoIP Home & Busi...
4,201597746111193,Promab customer protein project 2015-04-24,promab,promab@163.com,"""judy.tse@promab.com"" <judy.tse@promab.com>, M...","""promab8807@126.com"" <promab8807@126.com>",2015-04-24 00:27:27,"<div style=""line-height:1.7;color:#000000;font...",judy.tse@promab.com; martyn.lewis@promab.com; ...,judy.tse@promab.com; Martyn Lewis; promab8807@...,...,/Users/promab/anaconda_projects/email_agent/da...,True,1,[Promab customer protein project 2015-04-24.xls],X-Antivirus: Avast (VPS 15042801)\nX-Antivirus...,<136b8bd6.1efd9.14cea52f4f4.Coremail.promab@16...,,,eml,Promab customer protein project 2015-04-24.eml

In [10]:
df_all = pd.concat([df_pst_all, df_eml_all], ignore_index=True)

print("Final shape:", df_all.shape)
df_all.head()

Final shape: (228744, 21)

,id,subject,sender,sender_email,to,cc,date,body,recipient_emails,recipient_names,...,folder_path,has_attachments,attachment_count,attachment_names,headers,message_id,in_reply_to,references,source_type,source_file
0,2097988,答复: Stem cell medium technology purchase,LUO Rose,may8209@hotmail.com,judy.tse@promabinc.com,feihongoz@163.com,2018-02-28 00:41:33,"Dear Judy,\r\n\r\nThanks for your email.\r\n\r...",,,...,/Top of Outlook data file/Inbox,True,1,[image001.png],Delivered-To: judy.tse@promabinc.com\r\nReceiv...,<SG2PR01MB05698D16EC605F51C53192EFB9C70@SG2PR0...,<015001d3b023$013f83c0$03be8b40$@promabinc.com>,<HK2PR01MB05623323251A60276ECE25C9B9C00@HK2PR0...,pst,judy.tse@promabinc.com(4).pst
1,2098692,RE: Hybridoma Supernatant Timing,"Bates, Barbara",BBates@morgridge.org,judy.tse@promabinc.com,,2018-03-01 22:29:37,"Hello, \r\n\r\nI did receive your email. I thi...",,,...,/Top of Outlook data file/Inbox,False,0,[],Delivered-To: judy.tse@promabinc.com\r\nReceiv...,<F8B22F7FE52FD14FAAFB9ADA4F8DA9906AD43631@MIRI...,<012301d3b1ac$74187ed0$5c497c70$@promabinc.com>,<F8B22F7FE52FD14FAAFB9ADA4F8DA990585ADF22@MIRI...,pst,judy.tse@promabinc.com(4).pst
2,2098852,RE: Hybridoma Supernatant Timing,"Bates, Barbara",BBates@morgridge.org,judy.tse@promabinc.com,,2018-03-01 22:44:17,"I should have a formal PO to send tomorrow, bu...",,,...,/Top of Outlook data file/Inbox,False,0,[],Delivered-To: judy.tse@promabinc.com\r\nReceiv...,<F8B22F7FE52FD14FAAFB9ADA4F8DA9906AD4365B@MIRI...,<012301d3b1ac$74187ed0$5c497c70$@promabinc.com>,<F8B22F7FE52FD14FAAFB9ADA4F8DA990585ADF22@MIRI...,pst,judy.tse@promabinc.com(4).pst
3,2098948,答复: Stem cell medium technology purchase,LUO Rose,may8209@hotmail.com,judy.tse@promabinc.com,feihongoz@163.com,2018-03-02 12:20:48,"Dear Judy,\r\n\r\nWhat time will you be availa...",,,...,/Top of Outlook data file/Inbox,True,2,"[~WRD180.jpg, image001.png]",Delivered-To: judy.tse@promabinc.com\r\nReceiv...,<HK2PR01MB05621EF9E4B9BFB7CA37F52CB9C50@HK2PR0...,<01bc01d3b0cd$c7820e90$56862bb0$@promabinc.com>,<HK2PR01MB05623323251A60276ECE25C9B9C00@HK2PR0...,pst,judy.tse@promabinc.com(4).pst
4,2099268,RE: Stem cell medium technology purchase,john@promab.com,john@promab.com,judy.tse@promabinc.com,,2018-03-02 17:13:38,"Ask their wechat number so, we can call on wee...",,,...,/Top of Outlook data file/Inbox,True,2,"[image001.png, image002.jpg]",Delivered-To: judy.tse@promabinc.com\r\nReceiv...,<06f301d3b249$ccb27300$66175900$@promab.com>,<008f01d3b247$8b0e2ae0$a12a80a0$@promabinc.com>,<HK2PR01MB05623323251A60276ECE25C9B9C00@HK2PR0...,pst,judy.tse@promabinc.com(4).pst

In [11]:
df_all.to_parquet("../data/processed/df_all_emails.parquet", index=False)
print("saved.")

saved.

In [13]:
print("最早时间:", df_all["date"].min())
print("最晚时间:", df_all["date"].max())

最早时间: 2009-08-20 16:44:03
最晚时间: 2023-04-25 17:29:00